pipeline:
  step-a:
    image: golang
    commands:
      - date
      - bash drone/${COMMAND}.sh ${SHARD}
      - date

services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    when:
      matrix:
        - COMMAND: system-test
        - COMMAND: load-test


#  notify:
#    image: plugins/slack
#    channel: developers
#    username: drone

matrix:
  include:
    - COMMAND: lint
      SHARD: all
    - COMMAND: system-test
      SHARD: 1
    - COMMAND: system-test
      SHARD: 2
    - COMMAND: system-test
      SHARD: 3
    - COMMAND: load-test
      SHARD: all
