pipeline:
  compile:
    image: golang
    commands:
      - date
      - bash compile.sh
      - date

  lint:
    image: golang
    commands:
      - date
      - bash lint.sh
      - date
    when:
      matrix:
        SHARD: 1

  system-test:
    image: golang
    commands:
      - date
      - bash system-test.sh ${SHARD}
      - date

  # FIXME: We don't want to load test if system tests in other shards failed.
  load-test:
    image: golang
    commands:
      - date
      - bash load-test.sh ${SHARD}
      - date
    when:
      matrix:
        SHARD: 1

  # FIXME: We don't want to deploy if system tests in other shards failed.
  deploy-demo:
    image: golang
    commands:
      - date
      - bash deploy-demo.sh
      - date
    when:
      matrix:
        SHARD: 1

services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

#  notify:
#    image: plugins/slack
#    channel: developers
#    username: drone

matrix:
  include:
    - SHARD: 1
    - SHARD: 2
    - SHARD: 3
