pipeline:
  step-a:
    image: golang
    commands:
      - date
      - drone/${COMMAND}.sh ${SHARD}
      - date

#  notify:
#    image: plugins/slack
#    channel: developers
#    username: drone

matrix:
  include:
    - COMMAND: lint
      SHARD: all
    - COMMAND: system-test
      SHARD: 1
    - COMMAND: system-test
      SHARD: 2
    - COMMAND: system-test
      SHARD: 3
    - COMMAND: load-test
      SHARD: all
