pipeline:
  backend:
    image: golang
    commands:
      - true

  frontend:
    image: node:6
    commands:
      - true

#  notify:
#    image: plugins/slack
#    channel: developers
#    username: drone