pipeline:
  step-a:
    image: golang
    commands:
      - date
      - true

  step-b:
    image: golang
    commands:
      - date
      - echo ${PARALLEL_KEY}
      - sleep 30
      - date

  step-c:
    image: golang
    commands:
      - date
      - true

#  notify:
#    image: plugins/slack
#    channel: developers
#    username: drone

matrix:
  PARALLEL_KEY:
    - T1
    - T2
    - T3
    - T4
    - T5
    - T6
    - T7
    - T8
    - T9
    - T10
